# Generated by Django 5.2.4 on 2025-07-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task2',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
